import { ITitle, PLATE_FORM, TYPE } from "./typings.d";

const titlesConfig: ITitle[] = [
  {
    id: "crystal-defenders",
    title: "Crystal Defenders",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.UNOFFICIAL,
    logo: "crystal-defenders.png",
  },
  {
    id: "woff",
    title: "World of Final Fantasy",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.VITA],
    type: TYPE.SPIN_OFF,
    logo: "woff.png",
  },
  {
    id: "king-tale",
    title: "A King's Tale: Final Fantasy XV",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "king-tale.png",
  },
  {
    id: "monster-deep",
    title: "Monster of the Deep: Final Fantasy XV",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "monster-deep.png",
  },
  {
    id: "dissidia-nt",
    title: "Dissidia Final Fantasy NT",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "dissidia-nt.png",
  },
  {
    id: "dissidia-nt-free",
    title: "Dissidia Final Fantasy NT Free Edition",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "dissidia-nt-free.png",
  },
  {
    id: "15-3",
    title: "Final Fantasy XV Multiplayer: Comrades",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "15-3.png",
  },
  {
    id: "chocobo-dungeon",
    title: "Chocobo's Mystery Dungeon: Every Buddy!",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.UNOFFICIAL,
    logo: "chocobo-dungeon.png",
  },
  {
    id: "crystal-chronicles",
    title: "Final Fantasy Crystal Chronicles",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "crystal-chronicles.png",
  },
  {
    id: "07",
    title: "Final Fantasy VII",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "07.png",
  },
  {
    id: "08",
    title: "Final Fantasy VIII",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "08.png",
  },
  {
    id: "09",
    title: "Final Fantasy IX",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "09.png",
  },
  {
    id: "10",
    title: "Final Fantasy X HD",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.PS3, PLATE_FORM.VITA],
    type: TYPE.MAINLINE,
    logo: "10.png",
  },
  {
    id: "10-2",
    title: "Final Fantasy X-2 HD",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.PS3, PLATE_FORM.VITA],
    type: TYPE.MAINLINE,
    logo: "10-2.png",
  },
  {
    id: "12",
    title: "Final Fantasy XII: The Zodiac Age",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "12.png",
  },
  {
    id: "13",
    title: "Final Fantasy XIII",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "13.png",
  },
  {
    id: "13-2",
    title: "Final Fantasy XIII-2",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "13-2.png",
  },
  {
    id: "13-3",
    title: "Lightning Returns: Final Fantasy XIII",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "13-3.png",
  },
  {
    id: "type-0",
    title: "Final Fantasy Type-0 HD",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "type-0.png",
  },
  {
    id: "14",
    title: "Final Fantasy XIV: A Realm Reborn",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "14.png",
  },
  {
    id: "14-2",
    title: "Final Fantasy XIV",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.MAINLINE,
    logo: "14-2.png",
  },
  {
    id: "15",
    title: "Final Fantasy XV",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "15.png",
  },
  {
    id: "15-2",
    title: "Final Fantasy XV Pocket Edition HD",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "15-2.png",
  },
  {
    id: "07-2",
    title: "Final Fantasy VII Remake",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "07-2.png",
  },
  {
    id: "07-3",
    title: "Final Fantasy VII Remake",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.MAINLINE,
    logo: "07-3.png",
  },
  {
    id: "sopffo",
    title: "Stranger of Paradise: Final Fantasy Origin",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "sopffo.png",
  },
  {
    id: "sopffo-2",
    title: "Stranger of Paradise: Final Fantasy Origin",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.SPIN_OFF,
    logo: "sopffo-2.png",
  },
  {
    id: "adventures-mana",
    title: "Adventures of Mana",
    plate_forms: [PLATE_FORM.VITA],
    type: TYPE.UNOFFICIAL,
    logo: "adventures-mana.png",
  },
];

export { titlesConfig };
