import { ITitle, PLATE_FORM, TYPE } from "./typings.d";

const titlesConfig: ITitle[] = [
  {
    id: "crystal-defenders",
    title: "Crystal Defenders",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.UNOFFICIAL,
    logo: "crystal-defenders.png",
  },
  {
    id: "woff",
    title: "World of Final Fantasy",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.VITA],
    type: TYPE.SPIN_OFF,
    logo: "woff.png",
  },
  {
    id: "king-tale",
    title: "A King's Tale: Final Fantasy XV",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "king-tale.png",
  },
  {
    id: "monster-deep",
    title: "Monster of the Deep: Final Fantasy XV",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "monster-deep.png",
  },
  {
    id: "dissidia-nt",
    title: "Dissidia Final Fantasy NT",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "dissidia-nt.png",
  },
  {
    id: "dissidia-nt-free",
    title: "Dissidia Final Fantasy NT Free Edition",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "dissidia-nt-free.png",
  },
  {
    id: "15-3",
    title: "Final Fantasy XV Multiplayer: Comrades",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "15-3.png",
  },
  {
    id: "15-3-dlc-1",
    title: "FINAL FANTASY XV MULTIPLAYER: COMRADES December 2018 Update",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-3-dlc-1.png",
  },
  {
    id: "15-3-dlc-2",
    title: "FINAL FANTASY XV MULTIPLAYER: COMRADES March 2019 Update",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-3-dlc-2.png",
  },
  {
    id: "chocobo-dungeon",
    title: "Chocobo's Mystery Dungeon: Every Buddy!",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.UNOFFICIAL,
    logo: "chocobo-dungeon.png",
  },
  {
    id: "crystal-chronicles",
    title: "Final Fantasy Crystal Chronicles",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "crystal-chronicles.png",
  },
  {
    id: "07",
    title: "Final Fantasy VII",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "07.png",
  },
  {
    id: "07-2",
    title: "Final Fantasy VII Remake",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "07-2.png",
  },
  {
    id: "07-3",
    title: "Final Fantasy VII Remake",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.MAINLINE,
    logo: "07-3.png",
  },
  {
    id: "08",
    title: "Final Fantasy VIII",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "08.png",
  },
  {
    id: "09",
    title: "Final Fantasy IX",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "09.png",
  },
  {
    id: "10",
    title: "Final Fantasy X HD",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.PS3, PLATE_FORM.VITA],
    type: TYPE.MAINLINE,
    logo: "10.png",
  },
  {
    id: "10-2",
    title: "Final Fantasy X-2 HD",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.PS3, PLATE_FORM.VITA],
    type: TYPE.MAINLINE,
    logo: "10-2.png",
  },
  {
    id: "12",
    title: "Final Fantasy XII: The Zodiac Age",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "12.png",
  },
  {
    id: "13",
    title: "Final Fantasy XIII",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "13.png",
  },
  {
    id: "13-2",
    title: "Final Fantasy XIII-2",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "13-2.png",
  },
  {
    id: "13-3",
    title: "Lightning Returns: Final Fantasy XIII",
    plate_forms: [PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "13-3.png",
  },
  {
    id: "type-0",
    title: "Final Fantasy Type-0 HD",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "type-0.png",
  },
  {
    id: "14",
    title: "Final Fantasy XIV: A Realm Reborn",
    plate_forms: [PLATE_FORM.PS4, PLATE_FORM.PS3],
    type: TYPE.MAINLINE,
    logo: "14.png",
  },
  {
    id: "14-2",
    title: "Final Fantasy XIV",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.MAINLINE,
    logo: "14-2.png",
  },
  {
    id: "14-2-dlc-1",
    title: "Final Fantasy XIV: Heavensward",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-1.png",
  },
  {
    id: "14-2-dlc-2",
    title: "Final Fantasy XIV: Stormblood",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-2.png",
  },
  {
    id: "14-2-dlc-3",
    title: "Final Fantasy XIV: Shadowbringers",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-3.png",
  },
  {
    id: "14-2-dlc-4",
    title: "Final Fantasy XIV: Shadowbringers: Death Unto Dawn",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-4.png",
  },
  {
    id: "14-2-dlc-5",
    title: "Final Fantasy XIV: Endwalker",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-5.png",
  },
  {
    id: "14-2-dlc-6",
    title: "Final Fantasy XIV: Endwalker: Newfound Adventure",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-6.png",
  },
  {
    id: "14-2-dlc-7",
    title: "Final Fantasy XIV: Endwalker: Buried Memory",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-7.png",
  },
  {
    id: "14-2-dlc-8",
    title: "Final Fantasy XIV:  Endwalker: Gods Revel, Lands Tremble",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "14-2-dlc-8.png",
  },
  {
    id: "15",
    title: "Final Fantasy XV",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.MAINLINE,
    logo: "15.png",
  },
  {
    id: "15-dlc-1",
    title: "FINAL FANTASY XV: EPISODE GLADIOLUS",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-1.png",
  },
  {
    id: "15-dlc-2",
    title: "FINAL FANTASY XV: EPISODE PROMPTO",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-2.png",
  },
  {
    id: "15-dlc-3",
    title: "FINAL FANTASY XV: July 2017 Update",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-3.png",
  },
  {
    id: "15-dlc-4",
    title: "FINAL FANTASY XV MULTIPLAYER EXPANSION: COMRADES",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-4.png",
  },
  {
    id: "15-dlc-5",
    title: "FINAL FANTASY XV: EPISODE IGNIS",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-5.png",
  },
  {
    id: "15-dlc-6",
    title: "FINAL FANTASY XV: ROYAL PACK",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-6.png",
  },
  {
    id: "15-dlc-7",
    title: "FINAL FANTASY XV MULTIPLAYER EXPANSION: COMRADES March 2018 Update",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-7.png",
  },
  {
    id: "15-dlc-8",
    title: "FINAL FANTASY XV: EPISODE ARDYN",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "15-dlc-8.png",
  },
  {
    id: "15-2",
    title: "Final Fantasy XV Pocket Edition HD",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "15-2.png",
  },
  {
    id: "07-3-dlc-1",
    title: "Final Fantasy VII Remake: INTERmission",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "07-3-dlc-1.png",
  },
  {
    id: "sopffo",
    title: "Stranger of Paradise: Final Fantasy Origin",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "sopffo.png",
  },
  {
    id: "sopffo-dlc-1",
    title:
      "Stranger of Paradise: Final Fantasy Origin - Trials of the Dragon King",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "sopffo-dlc-1.png",
  },
  {
    id: "sopffo-dlc-2",
    title: "Stranger of Paradise: Final Fantasy Origin - Wanderer of the Rift",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "sopffo-dlc-2.png",
  },
  {
    id: "sopffo-dlc-3",
    title: "Stranger of Paradise: Final Fantasy Origin - DIFFERENT FUTURE",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.DLC,
    logo: "sopffo-dlc-3.png",
  },
  {
    id: "sopffo-2",
    title: "Stranger of Paradise: Final Fantasy Origin",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.SPIN_OFF,
    logo: "sopffo-2.png",
  },
  {
    id: "sopffo-2-dlc-1",
    title:
      "Stranger of Paradise: Final Fantasy Origin - Trials of the Dragon King",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "sopffo-2-dlc-1.png",
  },
  {
    id: "sopffo-2-dlc-2",
    title: "Stranger of Paradise: Final Fantasy Origin - Wanderer of the Rift",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "sopffo-2-dlc-2.png",
  },
  {
    id: "sopffo-2-dlc-3",
    title: "Stranger of Paradise: Final Fantasy Origin - DIFFERENT FUTURE",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.DLC,
    logo: "sopffo-2-dlc-3.png",
  },
  {
    id: "adventures-mana",
    title: "Adventures of Mana",
    plate_forms: [PLATE_FORM.VITA],
    type: TYPE.UNOFFICIAL,
    logo: "adventures-mana.png",
  },
  {
    id: "07-4",
    title: "Crisis Core: Final Fantasy VII - Reunion",
    plate_forms: [PLATE_FORM.PS5],
    type: TYPE.SPIN_OFF,
    logo: "07-4.png",
  },
  {
    id: "07-5",
    title: "Crisis Core: Final Fantasy VII - Reunion",
    plate_forms: [PLATE_FORM.PS4],
    type: TYPE.SPIN_OFF,
    logo: "07-5.png",
  },
];

export { titlesConfig };
